Repository Yoast/yoast-components, pull requests merged in 2018-08, with the labels that each got.

#679 Add all imports needed by wordpress seo to the export file.
  index.js
Labels: development done

#678 Implement cross with onClick functionality inside input container
  app/KeywordExample.js
  composites/Plugin/Shared/components/Button.js
  composites/Plugin/Shared/components/KeywordInput.js
  composites/Plugin/Shared/components/SvgIcon.js
  composites/Plugin/Shared/components/YoastInput.js
  composites/Plugin/Shared/tests/KeywordInputTest.js
  composites/Plugin/Shared/tests/__snapshots__/KeywordInputTest.js.snap
Labels: gutenberg, needs-acceptance

#684 Fix the standalone app demo pages after recent changes
  app/DashboardWidgetWrapper.js
  app/KeywordExample.js
Labels: needs-acceptance

#721 Bump YoastSEO.js to 1.39.0
  package.json
  yarn.lock
Labels: acceptance lingo
