Repository Yoast/yoast-components, pull requests merged in 2018-03, with the labels that each got.

#429 Make react-intl peer dependency
  README.md
  package.json
Labels: acceptance ★

#432 Fix typo in readme
  README.md
Labels: community-patch

#428 Implement Snippet Preview
  .babelrc
  .eslintrc
  App.js
  composites/Plugin/SnippetPreview/components/SnippetPreview.js
  composites/Plugin/SnippetPreview/components/SnippetPreviewExample.js
  composites/Plugin/SnippetPreview/components/fixedWidthContainer.js
  composites/Plugin/SnippetPreview/tests/SnippetPreviewTest.js
  composites/Plugin/SnippetPreview/tests/__snapshots__/SnippetPreviewTest.js.snap
  package.json
  yarn.lock
Labels: acceptance ★

#447 Added color value for no-index
  style-guide/_colors.scss
  style-guide/colors.json
Labels: needs-code-review
