Repository Yoast/yoast-components, pull requests merged in 2018-05, with the labels that each got.

#500 Change translation method for HelpCenter
  composites/Plugin/HelpCenter/HelpCenter.js
Labels: code-review ★

#501 Upgraded webpack to 4.7
  composites/AlgoliaSearch/tests/__snapshots__/SearchResultDetailTest.js.snap
  composites/Plugin/Shared/tests/__snapshots__/LinkButtonTest.js.snap
  composites/Plugin/Shared/tests/__snapshots__/YoastLinkButtonTest.js.snap
  composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
  composites/Plugin/SnippetPreview/tests/__snapshots__/SnippetPreviewTest.js.snap
  package.json
  webpack.config.js
  yarn.lock
Labels: needs-code-review ★

#508 Change translation method for Notification
  composites/basic/Notification.js
Labels: code-review ★

#513 CSS Solution for fixing the carret by the mobile description
  composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
  composites/Plugin/SnippetPreview/components/SnippetPreview.js
  composites/Plugin/SnippetPreview/tests/__snapshots__/SnippetPreviewTest.js.snap
Labels: needs-code-review ★

#506 Change translation method for SnippetEditor
  composites/Plugin/SnippetEditor/components/SnippetEditor.js
  composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
Labels: code-review ★

#515 Change slug field to input field instead of draftjs editor
  app/SnippetEditorExample.js
  composites/Plugin/SnippetEditor/components/ControlledInput.js
  composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
  composites/Plugin/SnippetEditor/tests/SnippetEditorTest.js
  composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
  composites/Plugin/SnippetPreview/components/ProgressBar.js
Labels: needs-code-review ★

#505 Change translation method for ContentAnalysis
  composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
  composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
Labels: code-review ★

#497 Change translation method for SearchBar
  composites/AlgoliaSearch/SearchBar.js
Labels: acceptance ★

#498 Change translation method for SearchResults
  composites/AlgoliaSearch/SearchResults.js
Labels: code-review ★

#523 Quick fix warning custom_field replacevars
  composites/Plugin/SnippetEditor/constants.js
Labels: acceptance ★

#527 Revert "Quick fix warning custom_field replacevars"
  composites/Plugin/SnippetEditor/constants.js
Labels: acceptance ★

#537 Replace replace vars before measuring the title and description length
  composites/Plugin/SnippetEditor/components/SnippetEditor.js
Labels: acceptance ★, snippet preview

#558 Bump YoastSEO.js to 1.33.1
  package.json
  yarn.lock
Labels: needs-acceptance lingo

#542 Snippet editor improve fields focus and blur
  app/SnippetEditorExample.js
  composites/Plugin/SnippetEditor/components/SnippetEditor.js
  composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
  composites/Plugin/SnippetEditor/tests/SnippetEditorTest.js
  composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
  composites/Plugin/SnippetPreview/components/SnippetPreview.js
  composites/Plugin/SnippetPreview/tests/SnippetPreviewTest.js
  composites/Plugin/SnippetPreview/tests/__snapshots__/SnippetPreviewTest.js.snap
Labels: in progress
