Repository Yoast/yoast-components, pull requests merged in 2018-07, with the labels that each got.

#639 Introduce wrapper in mock to pass innerRef as a ref and re-enable tests
  composites/Plugin/SnippetEditor/components/__mocks__/ReplacementVariableEditorStandalone.js
  composites/Plugin/SnippetEditor/tests/SnippetEditorTest.js
  composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
Labels: code-review ★

#640 Remove unused replaceKeyword
  README.md
  app/configureStore.js
  composites/Plugin/ContentAnalysis/actions/contentAnalysis.js
  composites/Plugin/ContentAnalysis/actions/tests/ContentAnalysisTest.js
  package.json
Labels: acceptance ★

#644 Fix propType of innerRef in mock
  composites/Plugin/SnippetEditor/components/__mocks__/ReplacementVariableEditorStandalone.js
Labels: acceptance ★

#487 Port yoast-premium-components to yoast-components
  App.js
  app/KeywordSuggestionWrapper.js
  composites/KeywordSuggestions/KeywordSuggestions.js
  composites/KeywordSuggestions/tests/KeywordSuggestionsTest.js
  composites/KeywordSuggestions/tests/__snapshots__/KeywordSuggestionsTest.js.snap
  composites/LinkSuggestions/LinkSuggestions.js
  composites/LinkSuggestions/LinkSuggestions.scss
  composites/LinkSuggestions/composites/LinkSuggestion.js
  dist/yoast-components-standalone.min.css
  dist/yoast-components.min.css
  index.js
  redux/actions/insights.js
  redux/actions/linkSuggestions.js
  redux/actions/tests/insightsTest.js
  redux/actions/tests/linkSuggestionsTest.js
  redux/reducers/index.js
  redux/reducers/insights.js
  redux/reducers/linkSuggestions.js
  redux/reducers/prominentWords.js
  redux/reducers/tests/indexTest.js
  redux/reducers/tests/insightsTest.js
  redux/reducers/tests/linkSuggestionsTest.js
  redux/reducers/tests/prominentWordsTest.js
Labels: acceptance

#649 Merge content analysis in sidebar feature branch into develop
  app/ContentAnalysisWrapper.js
  composites/Plugin/ContentAnalysis/actions/contentAnalysis.js
  composites/Plugin/ContentAnalysis/actions/tests/contentAnalysisTest.js
  composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
  composites/Plugin/ContentAnalysis/reducers/contentAnalysis/keywordResultsReducer.js
  composites/Plugin/ContentAnalysis/reducers/contentAnalysis/readabilityResultsReducer.js
  composites/Plugin/ContentAnalysis/reducers/tests/keywordResultsReducerTest.js
  composites/Plugin/ContentAnalysis/reducers/tests/readabilityResultsReducerTest.js
  composites/Plugin/ContentAnalysis/tests/ContentAnalysisTest.js
  composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
  grunt/config/eslint.js
  style-guide/colors.json
Labels: needs-code-review

#669 Bump YoastSEO.js to 1.36.0
  package.json
  yarn.lock
Labels: acceptance lingo

#674 Add demo page for the SVG icons.
  App.js
  app/SvgIconsWrapper.js
  composites/Plugin/Shared/components/SvgIcon.js
Labels: code-review
