Repository Yoast/yoast-components, pull requests merged in 2018-09, with the labels that each got.

#722 Refactor ContentAnalysis to expose AnalysisList
  composites/Plugin/ContentAnalysis/components/AnalysisList.js
  composites/Plugin/ContentAnalysis/components/ContentAnalysis.js
  composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
  index.js
Labels: acceptance

#726 Bump YoastSEO.js to 1.39.2
  package.json
  yarn.lock
Labels: acceptance

#732 Makes the string translatable
  composites/Plugin/SnippetEditor/components/SnippetEditor.js
Labels: code-review

#733 Load translation inside lifecycle function
  composites/Plugin/Shared/components/LanguageNotice.js
Labels: acceptance

#735 Move translation of the placeholder to the constructor
  composites/Plugin/SnippetEditor/components/SnippetEditor.js
  composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
Labels: needs-code-review

#734 Resolve no-shadow eslint errors
  .eslintrc
  composites/OnboardingWizard/OnboardingWizard.js
  composites/OnboardingWizard/helpers/ajaxHelper.js
  composites/Plugin/Shared/components/Collapsible.js
  composites/Plugin/SnippetEditor/components/SnippetEditor.js
  composites/Plugin/SnippetEditor/serialization.js
  composites/Plugin/SnippetEditor/tests/ReplacementVariableEditorTest.js
  composites/Plugin/SnippetPreview/components/SnippetPreview.js
Labels: acceptance, technical debt

#538 Set `currentColor` as default icon color
  composites/Plugin/Shared/components/SvgIcon.js
  composites/Plugin/Shared/tests/__snapshots__/CollapsibleTest.js.snap
  composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
Labels: community-patch, development done

#743 Fix import in the Snippet Preview demo.
  app/SnippetEditorExample.js
  composites/Plugin/SnippetEditor/components/SnippetEditor.js
Labels: needs-code-review
