Repository Yoast/yoast-components, pull requests merged in 2018-04, with the labels that each got.

#462 Add 2px padding to svg angles in analysisCollapsible
  composites/Plugin/ContentAnalysis/components/AnalysisCollapsible.js
  composites/Plugin/ContentAnalysis/tests/__snapshots__/AnalysisCollapsibleTest.js.snap
  composites/Plugin/ContentAnalysis/tests/__snapshots__/ContentAnalysisTest.js.snap
Labels: acceptance ★

#468 Configure label-has-for eslint rule
  .eslintrc
  composites/Plugin/Shared/components/A11yNotice.js
  composites/Plugin/Shared/components/Checkbox.js
  composites/Plugin/SnippetPreview/components/SnippetPreview.js
  forms/Label.js
Labels: acceptance ★

#460 Implements the snippet editor in React
  .codeclimate.yml
  App.js
  a11y/FormattedScreenReaderMessage.js
  a11y/ScreenReaderText.js
  app/SnippetEditorExample.js
  composites/Plugin/Shared/components/SvgIcon.js
  composites/Plugin/SnippetEditor/components/ModeSwitcher.js
  composites/Plugin/SnippetEditor/components/ReplacementVariableEditor.js
  composites/Plugin/SnippetEditor/components/SnippetEditor.js
  composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
  composites/Plugin/SnippetEditor/components/__mocks__/ReplacementVariableEditor.js
  composites/Plugin/SnippetEditor/constants.js
  composites/Plugin/SnippetEditor/index.js
  composites/Plugin/SnippetEditor/serialization.js
  composites/Plugin/SnippetEditor/tests/ReplacementVariableEditorTest.js
  composites/Plugin/SnippetEditor/tests/SnippetEditorTest.js
  composites/Plugin/SnippetEditor/tests/__snapshots__/ReplacementVariableEditorTest.js.snap
  composites/Plugin/SnippetEditor/tests/__snapshots__/SnippetEditorTest.js.snap
  composites/Plugin/SnippetEditor/tests/serializationTest.js
  composites/Plugin/SnippetPreview/components/FixedWidthContainer.js
  composites/Plugin/SnippetPreview/components/InputField.js
  composites/Plugin/SnippetPreview/components/ProgressBar.js
  composites/Plugin/SnippetPreview/components/SnippetPreview.js
  composites/Plugin/SnippetPreview/constants.js
  composites/Plugin/SnippetPreview/index.js
  composites/Plugin/SnippetPreview/tests/InputFieldTest.js
  composites/Plugin/SnippetPreview/tests/SnippetPreviewTest.js
  composites/Plugin/SnippetPreview/tests/__snapshots__/InputFieldTest.js.snap
  composites/Plugin/SnippetPreview/tests/__snapshots__/SnippetPreviewTest.js.snap
  forms/StyledSection/StyledSection.js
  forms/index.js
  index.html
  index.js
  package.json
  style-guide/_colors.scss
  style-guide/colors.json
  utils/helpers/intl-enzyme-test-helper.js
  utils/intlProvider.js
  webpack.config.js
  yarn.lock
Labels: needs-action ★

#478 Remove obsolete references in all.scss
  css/all.scss
Labels: needs-code-review ★
