Repository Yoast/yoast-components, pull requests merged in 2019-01, with the labels that each got.

#798 Add Underline and outboundlink to header.
  app/ComponentsExample.js
  composites/CoursesOverview/Card.js
  composites/CoursesOverview/CardDetails.js
  composites/CoursesOverview/tests/__snapshots__/CardDetailsTest.js.snap
  composites/CoursesOverview/tests/__snapshots__/CardTest.js.snap
  composites/Plugin/Shared/components/UpsellLinkButton.js
  grunt/config/eslint.js
Labels: needs-changes

#804 Upgrade webpack-dev-server to 3.1.14
  package.json
  yarn.lock
Labels: acceptance, has patch

#803 Add missing docblocks to Yoast-Components
  App.js
  app/AppWrapper.js
  app/KeywordExample.js
  app/KeywordSuggestionWrapper.js
  app/SnippetEditorExample.js
  app/SvgIconsWrapper.js
  app/WizardWrapper.js
  composites/AlgoliaSearch/AlgoliaSearcher.js
  composites/AlgoliaSearch/ArticleContent.js
  composites/OnboardingWizard/components/Choice.js
  composites/OnboardingWizard/tests/wizardTest.js
  composites/Plugin/CornerstoneContent/components/CornerstoneToggle.js
  composites/Plugin/DashboardWidget/components/WordpressFeed.js
  composites/Plugin/Shared/components/ScoreAssessments.js
  composites/Plugin/Shared/components/SectionTitle.js
  composites/Plugin/Shared/components/StackedProgressBar.js
  composites/Plugin/Shared/components/Toggle.js
  composites/Plugin/Shared/components/UpsellButton.js
  composites/Plugin/Shared/components/YoastModal.js
  composites/Plugin/Shared/tests/CollapsibleTest.js
  composites/Plugin/SnippetEditor/components/Mention.js
  composites/Plugin/SnippetEditor/components/ReplacementVariableEditor.js
  composites/Plugin/SnippetEditor/components/SettingsSnippetEditor.js
  composites/Plugin/SnippetEditor/components/SettingsSnippetEditorFields.js
  composites/Plugin/SnippetEditor/components/Shared.js
  composites/Plugin/SnippetEditor/components/SnippetEditor.js
  composites/Plugin/SnippetEditor/components/SnippetEditorFields.js
  composites/Plugin/SnippetEditor/components/__mocks__/ReplacementVariableEditorStandalone.js
  composites/Plugin/SnippetEditor/tests/SnippetEditorTest.js
  composites/Plugin/SnippetEditor/tests/serializationTest.js
  composites/Plugin/SnippetPreview/components/HelpTextWrapper.js
  composites/Plugin/SnippetPreview/components/SnippetPreview.js
  composites/Plugin/SnippetPreview/tests/SnippetPreviewTest.js
  composites/basic/ErrorBoundary.js
  composites/basic/Loader.js
  grunt/config/eslint.js
  render.js
  utils/i18n.js
  utils/intlProvider.js
Labels: yoast cs/qa
